[package]
name = "komb"
version = "0.2.1"
edition = "2021"
license = "MPL-2.0"
authors = ["Andrej KolÄin <self@kaathewise.net>"]
description = "A primitive parser combinator library"
repository = "https://github.com/kaathewisegit/komb"

[lints.rust]
missing_docs = "warn"
